### ISSUE TITLE
Could resp-server discover by Redis-Sentinel ?

### ISSUE THREAD

**Issue by aafri** [tonivade/resp-server#4]
Real redis can  integrated with Redis-Sentinel ,so redis is HA Redis becomes highly available。
Can resp-server be integrated with Sentinel?

**Comment by tonivade** [comment]
Hi @aafri 

resp-server is only a general purpose server that implements REDIS serialization protocol. Probably, you are referring to another of my projects, [claudb](https://github.com/tonivade/claudb), that it's an implementation of REDIS using Java. In claudb I have an [issue](https://github.com/tonivade/claudb/issues/15) to add sentinel support for claudb,  but now it's not supported.
